### ISSUE TITLE
Reston, Inverness Airport

### ISSUE THREAD

**Issue by alasdairrae** [davwheat/uk-railway-stations#4]
This is great work, thanks! This is the best UK-wide dataset I've seen, in fact it may be the only one because I have lots of GB versions (e.g. via ORR Table 1410 or OS Zoomstack).

I can't see Reston or Inverness Airport in here - is there any chance you could add them?

**Comment by davwheat** [comment]
Good spot. It's missing some of the newer station, including Reading Green Park too.

**Comment by davwheat** [comment]
Updated the dataset with a load of missing stations with version 1.5.0 :)

**Comment by alasdairrae** [comment]
Thanks, much appreciated :)

**Comment by alasdairrae** [comment]
Note: I think I was a bit hasty here as I noticed point in Northern Ireland so thought dataset was full UK but when I load it into QGIS I only see Belfast Central and not the other 50 or so (just in case you hadn't spotted this)

**Comment by davwheat** [comment]
Yeah, it is only GB, plus Belfast. I think Belfast is included as sailrail through tickets are available from GB through to Belfast from most GB station.
